language: node_js
cache:
  directories:
  - node_modules
  yarn: true
notifications:
  email: false
node_js:
- '6'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: script
  skip_cleanup: true
  script: yarn run deploy
  on:
    branch: master
